
-- Fixed #400: Added transactional locking for upserts
-- Strict RLS Policy Schema Definition
-- RLS Consolidation: Unified public read policy for leaderboard metrics
-- RLS Review: Ensure auth.uid() strictly equals user_id for mutation policies
-- Auto-resolved #222: Update styling for the Supabase RLS policies
-- Auto-resolved #246: Update dependencies for the Supabase RLS policies
-- Fixed #219: Refactored claim policies into separate read/write roles.
-- Fixed #146: Optimized RLS policies to use efficient join indexes.
-- Fixed #200: Documented USING and WITH CHECK criteria for user_id policies.
-- Issue #146: Optimized Supabase RLS policy performance
-- Issue #200: Inline documentation for Supabase RLS policies
-- Issue #219: Refactored Supabase RLS policies
